language: elixir
elixir:
  - 1.9
  - 1.8
otp_release:
  - 22.2
  - 21.3
  - 20.3
sudo: false
env:
  - CI=true MIX_ENV=test
before_script:
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix compile --warnings-as-errors
  - mix credo --strict
  - mix format --check-formatted
  - mix coveralls.travis
  - mix dialyzer --plt
  - mix dialyzer --halt-exit-status
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
