language: elixir
elixir:
  - 1.8
  - 1.7
  - 1.6
otp_release:
  - 21.3
  - 20.3
sudo: false
env:
  - MIX_ENV=test
before_script:
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix coveralls.travis
  - mix credo --strict
  - mix format --check-formatted
  - mix dialyzer --plt
  - mix dialyzer --halt-exit-status
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
